services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn prebo_tools.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
    restart: always

volumes:
  static_volume:
  media_volume:
