version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
    # command: gunicorn backend.wsgi:application --bind 0.0.0.0:8002
    command: python manage.py runserver 0.0.0.0:8002
    image: backend:latest
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - '8002:8002'
