# Generated by Django 5.1.6 on 2025-02-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_analyser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysedkeyword',
            options={'verbose_name': 'Analysed Keyword'},
        ),
    ]
