# Generated by Django 5.0.7 on 2024-07-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('feed_type', models.CharField(choices=[('wordpress', 'WordPress'), ('shopify', 'Shopify')], max_length=50)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xml', 'XML')], max_length=3)),
            ],
        ),
    ]
