# Generated by Django 5.0.7 on 2024-07-31 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_feed_optimiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='FeedResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField()),
                ('image_link', models.URLField()),
                ('availability', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('product_type', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('material', models.CharField(blank=True, max_length=255)),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=255)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_feed_optimiser.feed')),
            ],
        ),
    ]
