# Generated by Django 5.0.7 on 2024-07-31 18:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_feed_optimiser', '0002_alter_feed_name_feedresults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedresults',
            options={'verbose_name_plural': 'Feed Results'},
        ),
        migrations.RemoveField(
            model_name='feedresults',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='feedresults',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='feed',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedresults',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ai_feed_optimiser.feed'),
        ),
    ]
