# Generated by Django 5.0.7 on 2024-07-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_feed_optimiser', '0003_alter_feedresults_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedresults',
            name='identifier_exists',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
