# Generated by Django 5.0.7 on 2024-08-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_feed_optimiser', '0005_feedresults_custom_attributes_alter_feed_feed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
