# Generated by Django 5.0.7 on 2024-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_feed_optimiser', '0006_alter_feed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='limited_products',
            field=models.BooleanField(default=False),
        ),
    ]
