# Generated by Django 5.0.7 on 2024-09-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_feed_optimiser', '0007_feed_limited_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='limited_products',
        ),
    ]
