# Generated by Django 5.1.6 on 2026-08-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
