# Generated by Django 5.1.6 on 2026-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_gen', '0003_formsubmission_lead_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auto_email_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
