# Generated by Django 5.1.6 on 2026-07-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_gen', '0004_client_auto_email_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_leads_csv_export_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='leads_csv_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
