# Generated by Django 5.1.6 on 2026-07-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_gen', '0005_client_last_leads_csv_export_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notification_cc_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
